// waterService.ts
import { WaterItem } from "../types/water.d";

// Mock API call
export const getWaterItems = (): Promise<WaterItem[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: "1",
          name: "Distilled Water",
          type: "Distilled",
          price: "2.50",
          imageKey: "Item1",
          description: "Pure distilled water ideal for medical, laboratory, and drinking use.",
          rating: 4.8,
          ratingCount: 120,
          isAvailable: false,
        },
        {
          id: "2",
          name: "Spring Water",
          type: "Spring",
          price: "3.00",
          imageKey: "Item2",
          description: "Naturally sourced spring water from pristine mountain springs.",
          rating: 4.6,
          ratingCount: 98,
          isAvailable: false,
        },
        {
          id: "3",
          name: "Purified Water",
          type: "Purified",
          price: "2.75",
          imageKey: "Item3",
          description: "Multi-stage filtered water for excellent taste and clarity.",
          rating: 4.7,
          ratingCount: 145,
          isAvailable: false,
        },
        {
          id: "4",
          name: "Mineral Water",
          type: "Spring",
          price: "3.50",
          imageKey: "Item4",
          description: "Enriched with essential natural minerals for a healthy lifestyle.",
          rating: 4.9,
          ratingCount: 210,
          isAvailable: false,
        },
        {
          id: "5",
          name: "Alkaline Water",
          type: "Purified",
          price: "4.00",
          imageKey: "Item1",
          description: "Balanced pH alkaline water to keep your body refreshed and hydrated.",
          rating: 4.5,
          ratingCount: 85,
          isAvailable: false,
        },
        {
          id: "6",
          name: "Glacial Water",
          type: "Spring",
          price: "5.00",
          imageKey: "Item2",
          description: "Crystal clear glacial water, naturally cold and refreshing.",
          rating: 4.8,
          ratingCount: 132,
          isAvailable: false,
        },
        {
          id: "7",
          name: "Oxygenated Water",
          type: "Distilled",
          price: "3.25",
          imageKey: "Item3",
          description: "Enhanced with oxygen molecules for better hydration and energy.",
          rating: 4.4,
          ratingCount: 76,
          isAvailable: false,
        },
        {
          id: "8",
          name: "Filtered Water",
          type: "Purified",
          price: "2.80",
          imageKey: "Item4",
          description: "Triple-filtered water to remove impurities while preserving taste.",
          rating: 4.6,
          ratingCount: 101,
          isAvailable: false,
        },
        {
          id: "9",
          name: "Natural Spring Water",
          type: "Spring",
          price: "3.75",
          imageKey: "Item1",
          description: "Bottled directly from natural springs with balanced minerals.",
          rating: 4.7,
          ratingCount: 167,
          isAvailable: false,
        },
        {
          id: "10",
          name: "Electrolyte Water",
          type: "Distilled",
          price: "3.50",
          imageKey: "Item2",
          description: "Infused with essential electrolytes to keep you energized.",
          rating: 4.8,
          ratingCount: 140,
          isAvailable: false,
        },
      ]);
    }, 1500); // simulate network delay
  });
};
